version: "3"
services:
  gateway:
    image: traefik:v3.3.5
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@order-db:5432/order_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.orders.loadbalancer.server.port=5000"
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      order-db:
        condition: service_started

  order-service-2:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@order-db:5432/order_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.orders.loadbalancer.server.port=5000"
    depends_on:
      message-bus:
        condition: service_healthy
      order-db:
        condition: service_started

  order-db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=order_db
    volumes:
      - order-db:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=10
               -c max_wal_senders=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 1s
      retries: 10

  stock-service:
    build: ./stock
    image: stock:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@stock-db:5432/stock_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stock.rule=PathPrefix(`/stock`)"
      - "traefik.http.services.stock.loadbalancer.server.port=5000"
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      stock-db:
        condition: service_started
  
  stock-service-2:
    build: ./stock
    image: stock:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@stock-db:5432/stock_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stock.rule=PathPrefix(`/stock`)"
      - "traefik.http.services.stock.loadbalancer.server.port=5000"
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      stock-db:
        condition: service_started

  stock-db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_db
    volumes:
      - stock-db:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=10
               -c max_wal_senders=10
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 1s
      retries: 10

  payment-service:
    build: ./payment
    image: user:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@payment-db:5432/payment_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment`)"
      - "traefik.http.services.payment.loadbalancer.server.port=5000"
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      payment-db:
        condition: service_started

  payment-service-2:
    build: ./payment
    image: user:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@payment-db:5432/payment_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment`)"
      - "traefik.http.services.payment.loadbalancer.server.port=5000"
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      payment-db:
        condition: service_started

  payment-db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payment_db
    volumes:
      - payment-db:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_replication_slots=10
               -c max_wal_senders=10
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 1s
      retries: 10

  message-bus:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - message-bus:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  order-debezium:
    image: quay.io/debezium/server:3.1.0.Final
    volumes:
      - ./debezium-config/order.application.properties:/debezium/config/application.properties:readonly
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      order-db:
        condition: service_started

  stock-debezium:
    image: quay.io/debezium/server:3.1.0.Final
    volumes:
      - ./debezium-config/stock.application.properties:/debezium/config/application.properties:readonly
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      stock-db:
        condition: service_started

  payment-debezium:
    image: quay.io/debezium/server:3.1.0.Final
    volumes:
      - ./debezium-config/payment.application.properties:/debezium/config/application.properties:readonly
    restart: unless-stopped
    depends_on:
      message-bus:
        condition: service_healthy
      payment-db:
        condition: service_started

volumes:
  order-db:
    external: false
  stock-db:
    external: false
  payment-db:
    external: false
  message-bus:
    external: false