version: "3"
services:
  gateway:
    image: traefik:v3.3.5
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--log.level=INFO"
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: unless-stopped
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@order-db-primary:5432/order_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.orders.loadbalancer.server.port=5000"
    depends_on:
      message-bus:
        condition: service_healthy
      order-db-primary:
        condition: service_started

  order-service-2:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@order-db-primary:5432/order_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.orders.rule=PathPrefix(`/orders`)"
      - "traefik.http.services.orders.loadbalancer.server.port=5000"
    depends_on:
      message-bus:
        condition: service_healthy
      order-db-primary:
        condition: service_started

  order-db-primary:
    image: bitnami/postgresql-repmgr:17
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=order_db
      - POSTGRESQL_WAL_LEVEL=logical
      - REPMGR_PASSWORD=repmgr
      - REPMGR_NODE_ID=1
      - REPMGR_PRIMARY_HOST=order-db-primary
      - REPMGR_PARTNER_NODES=order-db-primary-1,order-db-replica-2
      - REPMGR_NODE_NAME=order-db-primary-1
      - REPMGR_NODE_NETWORK_NAME=order-db-primary
    volumes:
      - order-db-primary:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/postgresql-repmgr/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5

  order-db-replica:
    image: bitnami/postgresql-repmgr:17
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=order_db
      - REPMGR_PASSWORD=repmgr
      - REPMGR_NODE_ID=2
      - REPMGR_PRIMARY_HOST=order-db-primary
      - REPMGR_PARTNER_NODES=order-db-primary-1,order-db-replica-2
      - REPMGR_NODE_NAME=order-db-replica-2
      - REPMGR_NODE_NETWORK_NAME=order-db-replica
    volumes:
      - order-db-replica:/bitnami/postgresql
    depends_on:
      - order-db-primary
  stock-service:
    build: ./stock
    image: stock:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@stock-db-primary:5432/stock_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stock.rule=PathPrefix(`/stock`)"
      - "traefik.http.services.stock.loadbalancer.server.port=5000"
    depends_on:
      message-bus:
        condition: service_healthy
      stock-db-primary:
        condition: service_started
  
  stock-service-2:
    build: ./stock
    image: stock:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@stock-db-primary:5432/stock_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stock.rule=PathPrefix(`/stock`)"
      - "traefik.http.services.stock.loadbalancer.server.port=5000"
    depends_on:
      message-bus:
        condition: service_healthy
      stock-db-primary:
        condition: service_started

  stock-db-primary:
    image: bitnami/postgresql-repmgr:17
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=stock_db
      - POSTGRESQL_WAL_LEVEL=logical
      - REPMGR_PASSWORD=repmgr
      - REPMGR_NODE_ID=3
      - REPMGR_PRIMARY_HOST=stock-db-primary
      - REPMGR_PARTNER_NODES=stock-db-primary-3,stock-db-replica-4
      - REPMGR_NODE_NAME=stock-db-primary-3
      - REPMGR_NODE_NETWORK_NAME=stock-db-primary
    volumes:
      - stock-db-primary:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/postgresql-repmgr/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  stock-db-replica:
    image: bitnami/postgresql-repmgr:17
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=stock_db
      - REPMGR_PASSWORD=repmgr
      - REPMGR_NODE_ID=4
      - REPMGR_PRIMARY_HOST=stock-db-primary
      - REPMGR_PARTNER_NODES=stock-db-primary-3,stock-db-replica-4
      - REPMGR_NODE_NAME=stock-db-replica-4
      - REPMGR_NODE_NETWORK_NAME=stock-db-replica
    volumes:
      - stock-db-replica:/bitnami/postgresql
    depends_on:
      - stock-db-primary

  payment-service:
    build: ./payment
    image: user:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@payment-db-primary:5432/payment_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment`)"
      - "traefik.http.services.payment.loadbalancer.server.port=5000"
    depends_on:
      message-bus:
        condition: service_healthy
      payment-db-primary:
        condition: service_started


  payment-service-2:
    build: ./payment
    image: user:latest
    environment:
      - GATEWAY_URL=http://gateway:80
      - RABBIT_URL=amqp://guest:guest@message-bus:5672/
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@payment-db-primary:5432/payment_db
    command: gunicorn -b 0.0.0.0:5000 -w 3 -k uvicorn.workers.UvicornWorker --timeout 30 --log-level=info app:app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=PathPrefix(`/payment`)"
      - "traefik.http.services.payment.loadbalancer.server.port=5000"
    depends_on:
      message-bus:
        condition: service_healthy
      payment-db-primary:
        condition: service_started

  payment-db-primary:
    image: bitnami/postgresql-repmgr:17
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=payment_db
      - POSTGRESQL_WAL_LEVEL=logical
      - REPMGR_PASSWORD=repmgr
      - REPMGR_NODE_ID=5
      - REPMGR_PRIMARY_HOST=payment-db-primary
      - REPMGR_PARTNER_NODES=payment-db-primary-5,payment-db-replica-6
      - REPMGR_NODE_NAME=payment-db-primary-5
      - REPMGR_NODE_NETWORK_NAME=payment-db-primary
    volumes:
      - payment-db-primary:/bitnami/postgresql
    healthcheck:
      test: [ "CMD", "/opt/bitnami/scripts/postgresql-repmgr/healthcheck.sh" ]
      interval: 10s
      timeout: 5s
      retries: 5

  payment-db-replica:
    image: bitnami/postgresql-repmgr:17
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=payment_db
      - REPMGR_PASSWORD=repmgr
      - REPMGR_NODE_ID=6
      - REPMGR_PRIMARY_HOST=payment-db-primary
      - REPMGR_PARTNER_NODES=payment-db-primary-5,payment-db-replica-6
      - REPMGR_NODE_NAME=payment-db-replica-6
      - REPMGR_NODE_NETWORK_NAME=payment-db-replica
    volumes:
      - payment-db-replica:/bitnami/postgresql
    depends_on:
      - payment-db-primary

  message-bus:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - message-bus:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10

  order-debezium:
    image: quay.io/debezium/server:3.1.0.Final
    volumes:
      - ./debezium-config/order.application.properties:/debezium/config/application.properties:readonly
    depends_on:
      message-bus:
        condition: service_healthy
      order-db-primary:
        condition: service_started

  stock-debezium:
    image: quay.io/debezium/server:3.1.0.Final
    volumes:
      - ./debezium-config/stock.application.properties:/debezium/config/application.properties:readonly
    depends_on:
      message-bus:
        condition: service_healthy
      stock-db-primary:
        condition: service_started

  payment-debezium:
    image: quay.io/debezium/server:3.1.0.Final
    volumes:
      - ./debezium-config/payment.application.properties:/debezium/config/application.properties:readonly
    depends_on:
      message-bus:
        condition: service_healthy
      payment-db-primary:
        condition: service_started

volumes:
  order-db-primary:
    external: false
  order-db-replica:
    external: false
  stock-db-primary:
    external: false
  stock-db-replica:
    external: false
  payment-db-primary:
    external: false
  payment-db-replica:
    external: false
  message-bus:
    external: false